### PR TITLE
DM-24654: Add licensing headers to everything in alert-stream-simulator, and test for such headers

### PR DESCRIPTION
**Pull request by spenczar**
I forgot to do this. I'll keep forgetting to do this unless I write a test.

The test only checks `.py` files, not YAML docker configuration files or anything else. I think that's acceptable.

Putting headers in blank `__init__.py` feels a little odd, but I do it anyway because I guess it can't hurt.

### CODE REVIEW

**Comment by jonathansick** [comment]
I also see that there's a pre-commit hook for adding a license file https://github.com/Lucas-C/pre-commit-hooks I haven't tried it (I honestly haven't done much GPL-licensed stuff), but it's another way. It might be too fiddly with script hashbangs; I don't know.

**Comment by spenczar** [comment]
Thanks for the quick turnaround! Yeah, flake8 (and maybe autopep8) would be good to add, here. The hooks way is interesting but seems kinda complicated; I like that this test is really simple.

**Comment by jdswinbank** [comment]
I see this already merged so it's too late to do anything about it here, but... I noticed that the repository name is `alert-stream-simulator`, while the headers say `This file is part of rubin-alert-stream`. Is that intentional? Normally, we keep these in sync.

**Comment by spenczar** [comment]
@jdswinbank You're right, of course. That's an error. I'll fix in a quick branch.

**Pull request merged**
